version: 2.1

orbs:
  ruby: circleci/ruby@2.3.0

executors:
  default:
    docker:
      - image: cimg/ruby:3.3.5

jobs:
  test:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake test
  release:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake release

workflows:
  version: 2.1
  build:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
